# Generated by Django 4.0.6 on 2022-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='placephoto',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='placephoto',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
