# Generated by Django 4.0.6 on 2022-07-19 10:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_options_alter_placephoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('longitude', 'latitude')},
        ),
    ]
